name: twitch_chat
description: twitch_tchat allows dart and flutter apps to exploit the Twitch IRC with Emotes and Badges.
version: 1.3.2
homepage: https://github.com/LezdCS/twitch_chat
repository: https://github.com/LezdCS/twitch_chat

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.0
  collection: any
  dio: ^5.4.3+1
  uuid: ^4.4.0
  api_7tv: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
